### ISSUE TITLE
Cannot resolve servlet dependency

### ISSUE THREAD

**Issue by shashwatblack** [Studio-42/elfinder-servlet-demo#2]
This is what I have

```
    <dependency>
        <groupId>org.elfinder</groupId>
        <artifactId>elfinder-servlet</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </dependency>
```

Intellij doesn't seem to be able to find the dependency. I searched for it in the mvn central repository, but found nothing.

**Comment by anwfr** [comment]
hi,
Unfortunately the dependency is not available in mvn central yet.
You can get it from:
- the jar at https://github.com/Studio-42/elfinder-servlet/tree/master/jar
- build it from the source code (mvn install) at https://github.com/Studio-42/elfinder-servlet

Don't forget to update <version>1.2.0-SNAPSHOT</version> in your pom.xml

**Comment by shashwatblack** [comment]
Hello Antoine,

Thank you for the response. I did download the jar and included it in my `lib` folder. I'm having a weird issue though. Could you help me figure it out?
The details can be found here: http://stackoverflow.com/questions/31751107/

Warm Regards,
Shashwat
